import Foundation
import SVCore
import SVLearning
import SwiftData

/// View model for the song import sheet.
///
/// Manages the 4-tab import UI state, runs the import pipeline,
/// tracks progress, and saves the resulting `Song` to SwiftData.
@MainActor
@Observable
final class SongImportViewModel {

    // MARK: - Tab Selection

    /// The active tab in the import sheet.
    enum ImportTab: String, CaseIterable {
        case sargam = "Sargam"
        case western = "Western"
        case musicXML = "MusicXML"
        case mySongs = "My Songs"
    }

    var selectedTab: ImportTab = .western

    // MARK: - Edit Mode

    /// The existing song being edited, or nil when creating a new import.
    ///
    /// When non-nil, `startEdit()` replaces the song in-place instead of inserting a new one.
    private(set) var songBeingEdited: Song?

    /// Whether the view model is in edit mode (updating an existing song).
    var isEditMode: Bool { songBeingEdited != nil }

    // MARK: - Input Fields

    /// Notation text entered in the Sargam tab.
    var sargamText: String = ""

    /// Notation text entered in the Western tab.
    var westernText: String = ""

    /// MusicXML text pasted or loaded in the MusicXML tab.
    var musicXMLText: String = ""

    /// Song title entered by the user.
    var title: String = ""

    /// Artist or composer name.
    var artist: String = ""

    /// ISO 639-1 language code. Defaults to Hindi.
    var language: String = "hi"

    /// Difficulty level 1–5.
    var difficulty: Int = 1

    /// Song category.
    var category: String = "folk"

    // MARK: - Pipeline State

    /// Whether the import pipeline is currently running.
    private(set) var isImporting: Bool = false

    /// Current pipeline progress fraction (0.0–1.0).
    private(set) var progress: Double = 0.0

    /// Current pipeline stage name for display.
    private(set) var progressStageName: String = ""

    /// Warnings generated by the pipeline, pending user review.
    private(set) var pendingWarnings: [ParseWarning] = []

    /// Whether the warnings sheet is shown.
    var showWarnings: Bool = false

    /// Whether the import succeeded (triggers dismissal).
    private(set) var importSucceeded: Bool = false

    /// Error message to display if the import fails.
    ///
    /// Settable by the view layer to allow alert dismissal bindings to clear the error.
    var importError: String?

    // MARK: - Private

    private let pipeline = ImportPipeline()
    private let modelContext: ModelContext

    // MARK: - Initialisation

    /// Creates the view model with the SwiftData model context for saving songs.
    ///
    /// - Parameter modelContext: The context used to insert the imported `Song`.
    init(modelContext: ModelContext) {
        self.modelContext = modelContext
    }

    // MARK: - Public Methods

    /// Starts the import pipeline using the text from the currently selected tab.
    ///
    /// Validates that title and notation text are non-empty before starting.
    /// The pipeline runs on a background task; all UI state updates are
    /// dispatched back to `@MainActor` to avoid blocking the main thread.
    /// Emits analytics events for start, completion, and failure.
    func startImport() {
        let notationText: String
        let format: NotationInput.Format

        switch selectedTab {
        case .sargam:
            notationText = sargamText
            format = .sargam
        case .western:
            notationText = westernText
            format = .western
        case .musicXML:
            notationText = musicXMLText
            format = .musicXML
        case .mySongs:
            return // My Songs tab does not trigger import
        }

        guard !title.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
            importError = "Please enter a song title."
            return
        }

        guard !notationText.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
            importError = "Please enter notation text."
            return
        }

        isImporting = true
        progress = 0.0
        progressStageName = ""
        importError = nil
        pendingWarnings = []

        AnalyticsManager.shared.track(.songImportStarted, properties: [
            "format": format.rawValue,
            "title_length": title.count,
        ])

        // Capture value types before crossing isolation boundary
        let capturedTitle = title
        let capturedArtist = artist
        let capturedLanguage = language
        let capturedDifficulty = difficulty
        let capturedCategory = category

        let input = NotationInput(text: notationText, filenameHint: nil, declaredFormat: format)
        let stream = pipeline.run(
            input: input,
            title: capturedTitle,
            artist: capturedArtist,
            language: capturedLanguage,
            difficulty: capturedDifficulty,
            category: capturedCategory
        )

        // Consume the stream on a background task — dispatch UI updates to main actor.
        // This prevents blocking the main thread and keeps the UI responsive.
        // @MainActor is used for all state mutations; `self` is a class so capture is safe.
        Task {
            for await result in stream {
                switch result {
                case .progress(let update):
                    progress = update.fraction
                    progressStageName = update.stageName

                case .warningsGenerated(let warnings):
                    pendingWarnings = warnings
                    showWarnings = true
                    AnalyticsManager.shared.track(.songImportWarningDisplayed, properties: [
                        "warning_count": warnings.count,
                    ])

                case .completed(let dto):
                    saveToSwiftData(dto)
                    importSucceeded = true
                    AnalyticsManager.shared.track(.songImportCompleted, properties: [
                        "format": format.rawValue,
                        "note_count": dto.sargamNotationData?.count ?? dto.westernNotationData?.count ?? 0,
                        "has_midi": dto.midiData != nil,
                    ])

                case .failed(let error):
                    importError = error.localizedDescription
                    AnalyticsManager.shared.track(.songImportFailed, properties: [
                        "format": format.rawValue,
                        "error": error.localizedDescription,
                    ])
                }
                // Yield to the run loop so UI can update between pipeline stages
                await Task.yield()
            }
            isImporting = false
        }
    }

    /// Populates the form fields from an existing song for editing.
    ///
    /// Pre-fills title, artist, language, difficulty, category, tempo, and notation
    /// fields from the stored song. Sets `songBeingEdited` so that `startEdit()`
    /// will update in place instead of creating a new Song.
    ///
    /// - Parameter song: The user-imported song to edit.
    func loadForEditing(_ song: Song) {
        songBeingEdited = song
        title = song.title
        artist = song.artist
        language = song.language
        difficulty = song.difficulty
        category = song.category

        // Pre-fill the notation tab that has data, defaulting to Sargam
        if song.sargamNotation != nil {
            selectedTab = .sargam
            // Reconstruct text from stored notes so user can see and edit them
            if let notes = song.decodedSargamNotes {
                sargamText = notes.map { note in
                    var parts = [note.note]
                    if let mod = note.modifier { parts.insert(mod.capitalized, at: 0) }
                    return parts.joined(separator: " ")
                }.joined(separator: " ")
            }
        } else if song.westernNotation != nil {
            selectedTab = .western
            if let notes = song.decodedWesternNotes {
                westernText = notes.map { $0.note }.joined(separator: " ")
            }
        }
    }

    /// Starts the pipeline in edit mode — re-runs import and updates the existing song in place.
    ///
    /// Behaves identically to `startImport()` but calls `updateExistingSong()` on completion
    /// instead of inserting a new Song. The `songLibraryViewModel` applies the DTO to the song.
    ///
    /// - Parameter onComplete: Called on the main actor with the finished DTO when the pipeline succeeds.
    func startEdit(onComplete: @escaping @MainActor (ImportedSongDTO) -> Void) {
        let notationText: String
        let format: NotationInput.Format

        switch selectedTab {
        case .sargam:
            notationText = sargamText
            format = .sargam
        case .western:
            notationText = westernText
            format = .western
        case .musicXML:
            notationText = musicXMLText
            format = .musicXML
        case .mySongs:
            return
        }

        guard !title.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
            importError = "Please enter a song title."
            return
        }

        guard !notationText.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
            importError = "Please enter notation text."
            return
        }

        isImporting = true
        progress = 0.0
        progressStageName = ""
        importError = nil
        pendingWarnings = []

        let capturedTitle = title
        let capturedArtist = artist
        let capturedLanguage = language
        let capturedDifficulty = difficulty
        let capturedCategory = category

        let input = NotationInput(text: notationText, filenameHint: nil, declaredFormat: format)
        let stream = pipeline.run(
            input: input,
            title: capturedTitle,
            artist: capturedArtist,
            language: capturedLanguage,
            difficulty: capturedDifficulty,
            category: capturedCategory
        )

        Task {
            for await result in stream {
                switch result {
                case .progress(let update):
                    progress = update.fraction
                    progressStageName = update.stageName

                case .warningsGenerated(let warnings):
                    pendingWarnings = warnings
                    showWarnings = true

                case .completed(let dto):
                    onComplete(dto)
                    importSucceeded = true

                case .failed(let error):
                    importError = error.localizedDescription
                }
                await Task.yield()
            }
            isImporting = false
        }
    }

    /// Clears all input fields and resets state to initial values.
    func reset() {
        sargamText = ""
        westernText = ""
        musicXMLText = ""
        title = ""
        artist = ""
        language = "hi"
        difficulty = 1
        category = "folk"
        progress = 0.0
        progressStageName = ""
        pendingWarnings = []
        showWarnings = false
        importSucceeded = false
        importError = nil
        songBeingEdited = nil
    }

    // MARK: - Private Methods

    /// Saves the completed DTO as a `Song` @Model into SwiftData.
    ///
    /// Maps DTO fields to the correct `Song` property names, then inserts
    /// the model into the provided `ModelContext`.
    ///
    /// - Parameter dto: The fully validated import result from the pipeline.
    private func saveToSwiftData(_ dto: ImportedSongDTO) {
        let song = Song()
        song.title = dto.title
        song.artist = dto.artist
        song.language = dto.language
        song.difficulty = max(1, min(5, dto.difficulty))
        song.category = dto.category
        song.tempo = dto.tempo
        song.durationSeconds = dto.durationSeconds
        song.sargamNotation = dto.sargamNotationData
        song.westernNotation = dto.westernNotationData
        song.midiData = dto.midiData
        song.keySignatureRaw = dto.keySignature
        song.timeSignatureRaw = dto.timeSignature
        song.source = dto.source
        song.isFree = true
        song.sortOrder = 9999 // User songs sort after admin content
        modelContext.insert(song)
    }
}
