import Foundation

/// A piece of advice for the student based on practice performance.
///
/// Generated by `PracticeDifficultyAdvisor` to suggest next steps
/// based on recent accuracy trends.
public struct PracticeAdvice: Sendable, Equatable {
    /// Human-readable advice message.
    public let message: String

    /// Suggested action the student should take.
    public let suggestedAction: SuggestedAction

    public init(message: String, suggestedAction: SuggestedAction) {
        self.message = message
        self.suggestedAction = suggestedAction
    }
}

/// Actions that can be suggested to the student.
public enum SuggestedAction: String, Sendable, Equatable {
    /// Try the same song again at the same difficulty.
    case repeatSong
    /// Try an easier song or lower difficulty.
    case tryEasier
    /// Move on to a harder song or higher difficulty.
    case tryHarder
    /// Keep practicing — the student is improving.
    case keepPracticing
    /// Enable Wait Mode for more focused practice.
    case enableWaitMode
}
